//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Areas.Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_EmailSent
    {
        public string strMemberID { get; set; }
        public string strEMAIL { get; set; }
        public System.DateTime dtmCreate { get; set; }
        public Nullable<int> intSendCnt { get; set; }
        public Nullable<System.DateTime> dtmSendDate { get; set; }
        public string ysnSend { get; set; }
        public Nullable<bool> ysnActivate { get; set; }
        public Nullable<bool> ysnSendDone { get; set; }
    }
}
