//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Areas.Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SE_Member
    {
        public string strMemberID { get; set; }
        public string strContactID { get; set; }
        public string strCardID1 { get; set; }
        public string strCardID2 { get; set; }
        public string strEMail { get; set; }
        public string strPassword { get; set; }
        public string strName { get; set; }
        public string strMobile { get; set; }
        public string strPhone { get; set; }
        public Nullable<System.DateTime> dtmBirth { get; set; }
        public string strGender { get; set; }
        public Nullable<int> intZipCode { get; set; }
        public string strCity { get; set; }
        public string strZone { get; set; }
        public string strAddress { get; set; }
        public bool ysnPolicy { get; set; }
        public string strJoinTypeCode { get; set; }
        public string strJoinListCode { get; set; }
        public string strPicture { get; set; }
        public bool ysnActivate { get; set; }
        public string strActivateCode { get; set; }
        public string strMemberType { get; set; }
        public bool ysnActive { get; set; }
        public Nullable<System.DateTime> dtmActivated { get; set; }
        public Nullable<System.DateTime> dtmExpired { get; set; }
        public Nullable<System.DateTime> dtmVIPDate { get; set; }
        public bool ysnDM { get; set; }
        public bool ysnFax { get; set; }
        public bool ysnEmail { get; set; }
        public bool ysnSMS { get; set; }
        public bool ysnTel { get; set; }
        public string strMemo { get; set; }
        public System.DateTime ?dtmCreate { get; set; }
        public string strWHO { get; set; }
        public System.DateTime ?dtmUpdate { get; set; }
        public string strDisplayName { get; set; }
        public string strPhoneCity { get; set; }
        public string strReferrerID { get; set; }
        public string strFacebookID { get; set; }
    }
}
