//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mh.easyuse.com.tw/", ConfigurationName="ServiceReference.SendBatchSoap")]
    public interface SendBatchSoap {
        
        // CODEGEN: 命名空間 http://mh.easyuse.com.tw/ 的元素名稱  project_category_code 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://mh.easyuse.com.tw/SendTemplate", ReplyAction="*")]
        WebApplication3.ServiceReference.SendTemplateResponse SendTemplate(WebApplication3.ServiceReference.SendTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mh.easyuse.com.tw/SendTemplate", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference.SendTemplateResponse> SendTemplateAsync(WebApplication3.ServiceReference.SendTemplateRequest request);
        
        // CODEGEN: 命名空間 http://mh.easyuse.com.tw/ 的元素名稱  project_category_code 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://mh.easyuse.com.tw/SendTemplateWithBlock", ReplyAction="*")]
        WebApplication3.ServiceReference.SendTemplateWithBlockResponse SendTemplateWithBlock(WebApplication3.ServiceReference.SendTemplateWithBlockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mh.easyuse.com.tw/SendTemplateWithBlock", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference.SendTemplateWithBlockResponse> SendTemplateWithBlockAsync(WebApplication3.ServiceReference.SendTemplateWithBlockRequest request);
        
        // CODEGEN: 命名空間 http://mh.easyuse.com.tw/ 的元素名稱  remoteurl 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://mh.easyuse.com.tw/SendRemoteUrl", ReplyAction="*")]
        WebApplication3.ServiceReference.SendRemoteUrlResponse SendRemoteUrl(WebApplication3.ServiceReference.SendRemoteUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mh.easyuse.com.tw/SendRemoteUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference.SendRemoteUrlResponse> SendRemoteUrlAsync(WebApplication3.ServiceReference.SendRemoteUrlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTemplate", Namespace="http://mh.easyuse.com.tw/", Order=0)]
        public WebApplication3.ServiceReference.SendTemplateRequestBody Body;
        
        public SendTemplateRequest() {
        }
        
        public SendTemplateRequest(WebApplication3.ServiceReference.SendTemplateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mh.easyuse.com.tw/")]
    public partial class SendTemplateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int owner_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int template_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int group_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string project_category_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime send_date;
        
        public SendTemplateRequestBody() {
        }
        
        public SendTemplateRequestBody(int owner_id, int template_id, int group_id, string project_category_code, System.DateTime send_date) {
            this.owner_id = owner_id;
            this.template_id = template_id;
            this.group_id = group_id;
            this.project_category_code = project_category_code;
            this.send_date = send_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTemplateResponse", Namespace="http://mh.easyuse.com.tw/", Order=0)]
        public WebApplication3.ServiceReference.SendTemplateResponseBody Body;
        
        public SendTemplateResponse() {
        }
        
        public SendTemplateResponse(WebApplication3.ServiceReference.SendTemplateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mh.easyuse.com.tw/")]
    public partial class SendTemplateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendTemplateResult;
        
        public SendTemplateResponseBody() {
        }
        
        public SendTemplateResponseBody(int SendTemplateResult) {
            this.SendTemplateResult = SendTemplateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTemplateWithBlockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTemplateWithBlock", Namespace="http://mh.easyuse.com.tw/", Order=0)]
        public WebApplication3.ServiceReference.SendTemplateWithBlockRequestBody Body;
        
        public SendTemplateWithBlockRequest() {
        }
        
        public SendTemplateWithBlockRequest(WebApplication3.ServiceReference.SendTemplateWithBlockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mh.easyuse.com.tw/")]
    public partial class SendTemplateWithBlockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int owner_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int template_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int group_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string project_category_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime send_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int blocklist_id;
        
        public SendTemplateWithBlockRequestBody() {
        }
        
        public SendTemplateWithBlockRequestBody(int owner_id, int template_id, int group_id, string project_category_code, System.DateTime send_date, int blocklist_id) {
            this.owner_id = owner_id;
            this.template_id = template_id;
            this.group_id = group_id;
            this.project_category_code = project_category_code;
            this.send_date = send_date;
            this.blocklist_id = blocklist_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTemplateWithBlockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTemplateWithBlockResponse", Namespace="http://mh.easyuse.com.tw/", Order=0)]
        public WebApplication3.ServiceReference.SendTemplateWithBlockResponseBody Body;
        
        public SendTemplateWithBlockResponse() {
        }
        
        public SendTemplateWithBlockResponse(WebApplication3.ServiceReference.SendTemplateWithBlockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mh.easyuse.com.tw/")]
    public partial class SendTemplateWithBlockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendTemplateWithBlockResult;
        
        public SendTemplateWithBlockResponseBody() {
        }
        
        public SendTemplateWithBlockResponseBody(int SendTemplateWithBlockResult) {
            this.SendTemplateWithBlockResult = SendTemplateWithBlockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRemoteUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRemoteUrl", Namespace="http://mh.easyuse.com.tw/", Order=0)]
        public WebApplication3.ServiceReference.SendRemoteUrlRequestBody Body;
        
        public SendRemoteUrlRequest() {
        }
        
        public SendRemoteUrlRequest(WebApplication3.ServiceReference.SendRemoteUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mh.easyuse.com.tw/")]
    public partial class SendRemoteUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int owner_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remoteurl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string remoteurlcharset;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int group_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string project_category_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime send_date;
        
        public SendRemoteUrlRequestBody() {
        }
        
        public SendRemoteUrlRequestBody(int owner_id, string remoteurl, string remoteurlcharset, int group_id, string project_category_code, System.DateTime send_date) {
            this.owner_id = owner_id;
            this.remoteurl = remoteurl;
            this.remoteurlcharset = remoteurlcharset;
            this.group_id = group_id;
            this.project_category_code = project_category_code;
            this.send_date = send_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRemoteUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRemoteUrlResponse", Namespace="http://mh.easyuse.com.tw/", Order=0)]
        public WebApplication3.ServiceReference.SendRemoteUrlResponseBody Body;
        
        public SendRemoteUrlResponse() {
        }
        
        public SendRemoteUrlResponse(WebApplication3.ServiceReference.SendRemoteUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mh.easyuse.com.tw/")]
    public partial class SendRemoteUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendRemoteUrlResult;
        
        public SendRemoteUrlResponseBody() {
        }
        
        public SendRemoteUrlResponseBody(int SendRemoteUrlResult) {
            this.SendRemoteUrlResult = SendRemoteUrlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendBatchSoapChannel : WebApplication3.ServiceReference.SendBatchSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendBatchSoapClient : System.ServiceModel.ClientBase<WebApplication3.ServiceReference.SendBatchSoap>, WebApplication3.ServiceReference.SendBatchSoap {
        
        public SendBatchSoapClient() {
        }
        
        public SendBatchSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendBatchSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendBatchSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendBatchSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication3.ServiceReference.SendTemplateResponse WebApplication3.ServiceReference.SendBatchSoap.SendTemplate(WebApplication3.ServiceReference.SendTemplateRequest request) {
            return base.Channel.SendTemplate(request);
        }
        
        public int SendTemplate(int owner_id, int template_id, int group_id, string project_category_code, System.DateTime send_date) {
            WebApplication3.ServiceReference.SendTemplateRequest inValue = new WebApplication3.ServiceReference.SendTemplateRequest();
            inValue.Body = new WebApplication3.ServiceReference.SendTemplateRequestBody();
            inValue.Body.owner_id = owner_id;
            inValue.Body.template_id = template_id;
            inValue.Body.group_id = group_id;
            inValue.Body.project_category_code = project_category_code;
            inValue.Body.send_date = send_date;
            WebApplication3.ServiceReference.SendTemplateResponse retVal = ((WebApplication3.ServiceReference.SendBatchSoap)(this)).SendTemplate(inValue);
            return retVal.Body.SendTemplateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference.SendTemplateResponse> WebApplication3.ServiceReference.SendBatchSoap.SendTemplateAsync(WebApplication3.ServiceReference.SendTemplateRequest request) {
            return base.Channel.SendTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication3.ServiceReference.SendTemplateResponse> SendTemplateAsync(int owner_id, int template_id, int group_id, string project_category_code, System.DateTime send_date) {
            WebApplication3.ServiceReference.SendTemplateRequest inValue = new WebApplication3.ServiceReference.SendTemplateRequest();
            inValue.Body = new WebApplication3.ServiceReference.SendTemplateRequestBody();
            inValue.Body.owner_id = owner_id;
            inValue.Body.template_id = template_id;
            inValue.Body.group_id = group_id;
            inValue.Body.project_category_code = project_category_code;
            inValue.Body.send_date = send_date;
            return ((WebApplication3.ServiceReference.SendBatchSoap)(this)).SendTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication3.ServiceReference.SendTemplateWithBlockResponse WebApplication3.ServiceReference.SendBatchSoap.SendTemplateWithBlock(WebApplication3.ServiceReference.SendTemplateWithBlockRequest request) {
            return base.Channel.SendTemplateWithBlock(request);
        }
        
        public int SendTemplateWithBlock(int owner_id, int template_id, int group_id, string project_category_code, System.DateTime send_date, int blocklist_id) {
            WebApplication3.ServiceReference.SendTemplateWithBlockRequest inValue = new WebApplication3.ServiceReference.SendTemplateWithBlockRequest();
            inValue.Body = new WebApplication3.ServiceReference.SendTemplateWithBlockRequestBody();
            inValue.Body.owner_id = owner_id;
            inValue.Body.template_id = template_id;
            inValue.Body.group_id = group_id;
            inValue.Body.project_category_code = project_category_code;
            inValue.Body.send_date = send_date;
            inValue.Body.blocklist_id = blocklist_id;
            WebApplication3.ServiceReference.SendTemplateWithBlockResponse retVal = ((WebApplication3.ServiceReference.SendBatchSoap)(this)).SendTemplateWithBlock(inValue);
            return retVal.Body.SendTemplateWithBlockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference.SendTemplateWithBlockResponse> WebApplication3.ServiceReference.SendBatchSoap.SendTemplateWithBlockAsync(WebApplication3.ServiceReference.SendTemplateWithBlockRequest request) {
            return base.Channel.SendTemplateWithBlockAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication3.ServiceReference.SendTemplateWithBlockResponse> SendTemplateWithBlockAsync(int owner_id, int template_id, int group_id, string project_category_code, System.DateTime send_date, int blocklist_id) {
            WebApplication3.ServiceReference.SendTemplateWithBlockRequest inValue = new WebApplication3.ServiceReference.SendTemplateWithBlockRequest();
            inValue.Body = new WebApplication3.ServiceReference.SendTemplateWithBlockRequestBody();
            inValue.Body.owner_id = owner_id;
            inValue.Body.template_id = template_id;
            inValue.Body.group_id = group_id;
            inValue.Body.project_category_code = project_category_code;
            inValue.Body.send_date = send_date;
            inValue.Body.blocklist_id = blocklist_id;
            return ((WebApplication3.ServiceReference.SendBatchSoap)(this)).SendTemplateWithBlockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication3.ServiceReference.SendRemoteUrlResponse WebApplication3.ServiceReference.SendBatchSoap.SendRemoteUrl(WebApplication3.ServiceReference.SendRemoteUrlRequest request) {
            return base.Channel.SendRemoteUrl(request);
        }
        
        public int SendRemoteUrl(int owner_id, string remoteurl, string remoteurlcharset, int group_id, string project_category_code, System.DateTime send_date) {
            WebApplication3.ServiceReference.SendRemoteUrlRequest inValue = new WebApplication3.ServiceReference.SendRemoteUrlRequest();
            inValue.Body = new WebApplication3.ServiceReference.SendRemoteUrlRequestBody();
            inValue.Body.owner_id = owner_id;
            inValue.Body.remoteurl = remoteurl;
            inValue.Body.remoteurlcharset = remoteurlcharset;
            inValue.Body.group_id = group_id;
            inValue.Body.project_category_code = project_category_code;
            inValue.Body.send_date = send_date;
            WebApplication3.ServiceReference.SendRemoteUrlResponse retVal = ((WebApplication3.ServiceReference.SendBatchSoap)(this)).SendRemoteUrl(inValue);
            return retVal.Body.SendRemoteUrlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference.SendRemoteUrlResponse> WebApplication3.ServiceReference.SendBatchSoap.SendRemoteUrlAsync(WebApplication3.ServiceReference.SendRemoteUrlRequest request) {
            return base.Channel.SendRemoteUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication3.ServiceReference.SendRemoteUrlResponse> SendRemoteUrlAsync(int owner_id, string remoteurl, string remoteurlcharset, int group_id, string project_category_code, System.DateTime send_date) {
            WebApplication3.ServiceReference.SendRemoteUrlRequest inValue = new WebApplication3.ServiceReference.SendRemoteUrlRequest();
            inValue.Body = new WebApplication3.ServiceReference.SendRemoteUrlRequestBody();
            inValue.Body.owner_id = owner_id;
            inValue.Body.remoteurl = remoteurl;
            inValue.Body.remoteurlcharset = remoteurlcharset;
            inValue.Body.group_id = group_id;
            inValue.Body.project_category_code = project_category_code;
            inValue.Body.send_date = send_date;
            return ((WebApplication3.ServiceReference.SendBatchSoap)(this)).SendRemoteUrlAsync(inValue);
        }
    }
}
